### ISSUE TITLE
Javascript Unit Tets

### ISSUE THREAD

**Issue by jonswaino** [MarlabsInc/webapi-angularjs-spa#1]
Any chance you could add Karma/Jasmine Unit tests to this project?  It would really put the icing on the cake if you could demonstrate this, especially considering that AngularJS has been built with testability in mind,

**Comment by shijuvar** [comment]
@jonswaino - We are going for a major code refactoring in this app and will provide unit tests to this project  by leveraging Karma/Jasmine.

**Comment by jonswaino** [comment]
Great that is good to hear.

**Comment by yuren1978** [comment]
This is a great start project for AngularJS, I learned a lot by reading through the source code.

**Comment by shijuvar** [comment]
@yuren1978 - Thanks, I am glad to hear that it has been helpful to you.

**Comment by shijuvar** [comment]
@jonswaino - The current drop contains unit tests with Jasmine.

**Comment by israelpereira** [comment]
Amazing sample, Thank you so much, I'm studying Jasmine and Karma with angularJS, web API.. and it is helping me a lot
