### ISSUE TITLE
It would be great if you could integrate the asp.net identity in your example.

### ISSUE THREAD

**Issue by yuren1978** [MarlabsInc/webapi-angularjs-spa#3]
It would be great if you could integrate the asp.net identity in your example.

**Comment by shijuvar** [comment]
@yuren1978 - We will integrate ASP.NET Identity on the next refactor cycle for server-side implementations.

**Comment by yuren1978** [comment]
Looks like it's already there, you guys rock, I will check to see if I can make some contriubutions to this project.

**Comment by shijuvar** [comment]
@yuren1978  - This is an ongoing project, and we would greatly appreciate contributions.

**Comment by dmolesky** [comment]
I'm having trouble getting the external auth working with CORS. Since the client is hosted on a different web-server than the API project. Can the built in external auth still be leveraged?

**Comment by shijuvar** [comment]
We have already enabled CORS for the API project.
