### ISSUE TITLE
Missing files/Broken references

### ISSUE THREAD

**Issue by kyleballard** [MarlabsInc/webapi-angularjs-spa#4]
Several files in the cloned repo, or downloadable zip, are missing.  

/Scripts/app/ngscripts.js
/Scripts/libs/angular-ui/select2.min.js
/Scripts/libs/select2/select2.min.js
/Scripts/libs/jquery-1.9.1.min.js

**Comment by shijuvar** [comment]
Please ensure you are running Gulp tasks, which will create the minified JavaScript files.
