### ISSUE TITLE
Move this kind of Project into a template

### ISSUE THREAD

**Issue by kjellski** [MarlabsInc/webapi-angularjs-spa#5]
Hey there, 

I'm really enjoying your project examples, is there any chance to get these out as a project template on the MS library? It would be absolutely awesome to just pull it from inside VS and start your own project with this solid foundation :)

Anyways, great job so far, very much appreciated!

**Comment by shijuvar** [comment]
@kjellski - Thanks for the appreciation and feedback. We will definitely look on this after completing other prioritized work items. I would also encourage developer communities to contribute for this project and working on things like this.
